name: GHES/GHEC repos to GitHub migration [GEI]
description: Perform a migration of repos from GHES or GHEC to GitHub using GEI
title: "GHES/GHEC repos to GitHub migration [GEI]"
labels: ["migration", "gei"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitHub Enterprise Server to GitHub Enterprise Cloud
      placeholder: |
        https://github.com/your-org/your-repository-1
        https://github.com/your-org/your-repository-2
    validations:
      required: true
  - type: dropdown
    id: organization
    attributes:
      label: Target Organization
      description: Please select the Target Organization
      options:
        - mgmri-commerce
        - mgmri-source
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub Enterprise Cloud after they have been migrated
      options:
        - Private
        - Internal
        - Mirror
    validations:
      required: true
  - type: dropdown
    id: lock_source_repo
    attributes:
      label: Lock Source Repository
      description: Select "Yes" to lock the source repository after migration, or "No" to leave it unlocked.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
